services:

  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    volumes:
      - ./api:/app
      - ./api/node_modules:/app/node_modules
    command: npm run start:prod
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@host.docker.internal:5432/tradebotdb
      MESSAGE_URL: amqp://host.docker.internal:5672
      LOG_FOLDER: /Users/vimalkrishnan/temp/logs/tradebot
    ports:
      - 9090:3000
    networks:
      - local
  
  rabbitmq:
    image: rabbitmq:3
    ports:
      - '5672:5672'
    networks:
      - local
        
  postgres:
    image: postgres:14
    restart: always
    container_name: db
    volumes:
      - tradebotdata:/var/lib/postgresql/data
    networks:  
      - local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tradebotdb
    ports:
      - 5432:5432
  
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    command: ng serve --configuration production
    depends_on:
      - api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 9390:4300
    networks:
      - local
      
networks:
  local:

volumes:
    tradebotdata:
        external: true